trigger:
- main
- master

pool:
  name: 'Mylerz-Test-Pool'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: BuildAndDeployStage
  displayName: 'Build and Deploy to IIS'
  jobs:
  - job: CICDJob
    steps:
    # 1. تحميل الـ NuGet Packages
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    # 2. عمل الـ Build وإخراج ملف الـ Web Deploy في الباص المظبوط
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    # 3. رفع الـ Artifact للـ Azure DevOps (عشان تفضل النسخة معاك)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    # 4. الـ Auto Deployment السحري على الـ IIS عندك في السيرفر عل طول!
    - task: IISWebAppDeploymentOnMachineGroup@0
      displayName: 'Deploy to Local IIS Website'
      inputs:
        WebSiteName: 'DemoAppSite' # اسم الموقع اللي عملناه في الـ IIS
        Package: '$(Build.ArtifactStagingDirectory)\WebApp.zip'